#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

terraform fmt .
terraform init
terraform plan -var="full_path=${DIR}" -var-file=${DIR}/vars/common.tfvars -out "$DIR/outputs/tf.output" $1
